//! v2 harness for the `promqltest` corpus.
//!
//! This mirrors [`super::runner::run_test`] but routes evaluation through
//! `Tsdb::eval_query_v2` instead of `Tsdb::eval_query`. It exists so RFC 0007
//! Phase 6 can run the unmodified `.test` fixtures against the v2 engine and
//! triage failures without touching the v1 harness.
//!
//! Intentionally duplicates the runner rather than parameterising it: the v1
//! path is the correctness oracle for other suites that depend on the existing
//! harness shape, and keeping the v2 router in a separate file makes the diff
//! easy to review and the v1 code path unchanged.
//!
//! **Do not edit fixtures under `testdata/`** — RFC 0007 Phase 6 hard rule §1.4.

#![cfg(feature = "promql-v2")]

use crate::model::{QueryOptions, RangeSample};
use crate::promql::promqltest::assert::assert_results;
use crate::promql::promqltest::dsl::*;
use crate::promql::promqltest::loader::load_series;
use crate::storage::merge_operator::OpenTsdbMergeOperator;
use crate::tsdb::Tsdb;
use common::storage::in_memory::InMemoryStorage;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::SystemTime;

/// v2 analogue of [`super::evaluator::eval_instant`]. Routes through
/// `Tsdb::eval_query_v2` and coerces the `QueryValue` to `Vec<RangeSample>`
/// so it is directly comparable to the v1 path via [`assert_results`].
async fn eval_instant_v2(
    tsdb: &Tsdb,
    time: SystemTime,
    query: &str,
) -> Result<Vec<RangeSample>, String> {
    tsdb.eval_query_v2(query, Some(time), &QueryOptions::default())
        .await
        .map_err(|e| e.to_string())
        .map(|qv| qv.into_matrix())
}

fn new_test_storage() -> Tsdb {
    let storage = Arc::new(InMemoryStorage::with_merge_operator(Arc::new(
        OpenTsdbMergeOperator,
    )));
    Tsdb::new(storage)
}

/// Run a single `.test` fixture through the v2 engine. Structure mirrors
/// [`super::runner::run_test`] with one deliberate difference: eval-level
/// failures are **collected**, not short-circuited, so a single corpus run
/// surfaces every failure per file rather than stopping at the first.
/// `Load`/`Clear`/`parse_test_file` errors remain fatal because they break
/// the remaining eval invariants.
pub async fn run_test_v2(name: &str, content: &str) -> Result<(), String> {
    let commands = parse_test_file(content)?;
    let mut tsdb = new_test_storage();
    let mut eval_count = 0;
    let mut ignoring = false;
    let mut failures: Vec<String> = Vec::new();

    for cmd in commands {
        match cmd {
            Command::Clear(_) => {
                tsdb = new_test_storage();
            }
            Command::Ignore(_) => {
                ignoring = true;
            }
            Command::Resume(_) => {
                ignoring = false;
            }
            Command::Load(load_cmd) => {
                if !ignoring {
                    load_series(&tsdb, load_cmd.interval, &load_cmd.series).await?;
                }
            }
            Command::EvalInstant(eval_cmd) => {
                if !ignoring {
                    eval_count += 1;
                    match eval_instant_v2(&tsdb, eval_cmd.time, &eval_cmd.query).await {
                        Ok(result) => {
                            if let Err(e) = assert_results(
                                &result,
                                &eval_cmd.expected,
                                eval_cmd.expect_ordered,
                                name,
                                eval_count,
                                &eval_cmd.query,
                            ) {
                                failures.push(e);
                            }
                        }
                        Err(e) => {
                            failures.push(format!(
                                "{} eval #{} (query: {}): {}",
                                name, eval_count, eval_cmd.query, e
                            ));
                        }
                    }
                }
            }
        }
    }

    if failures.is_empty() {
        Ok(())
    } else {
        Err(failures.join("\n"))
    }
}

/// Discover every `.test` file under `testdata/` (same directory the v1
/// harness reads).
fn discover_test_files() -> Vec<PathBuf> {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("src")
        .join("promql")
        .join("promqltest")
        .join("testdata");

    let mut files: Vec<PathBuf> = std::fs::read_dir(&dir)
        .expect("failed to read testdata directory")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("test"))
        .collect();
    files.sort();
    files
}

/// Per-file v2 tests — one `#[tokio::test]` per fixture so failures land on a
/// specific file rather than a single aggregated failure. Generated by hand
/// because `build.rs` emits the v1 harness tests; extending `build.rs` would
/// touch shared infrastructure for a Phase-6-only purpose.
#[cfg(test)]
mod tests {
    use super::*;

    async fn run_fixture(stem: &str) -> Result<(), String> {
        let path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("src")
            .join("promql")
            .join("promqltest")
            .join("testdata")
            .join(format!("{stem}.test"));
        let content = std::fs::read_to_string(&path)
            .map_err(|e| format!("failed to read fixture {stem}: {e}"))?;
        run_test_v2(stem, &content).await
    }

    #[tokio::test(flavor = "multi_thread", worker_threads = 2)]
    async fn should_pass_aggregators_v2() {
        run_fixture("aggregators").await.unwrap();
    }

    #[tokio::test(flavor = "multi_thread", worker_threads = 2)]
    async fn should_pass_at_modifier_v2() {
        run_fixture("at_modifier").await.unwrap();
    }

    #[tokio::test(flavor = "multi_thread", worker_threads = 2)]
    async fn should_pass_functions_v2() {
        run_fixture("functions").await.unwrap();
    }

    #[tokio::test(flavor = "multi_thread", worker_threads = 2)]
    async fn should_pass_name_label_dropping_v2() {
        run_fixture("name_label_dropping").await.unwrap();
    }

    #[tokio::test(flavor = "multi_thread", worker_threads = 2)]
    async fn should_pass_offset_v2() {
        run_fixture("offset").await.unwrap();
    }

    #[tokio::test(flavor = "multi_thread", worker_threads = 2)]
    async fn should_pass_operators_v2() {
        run_fixture("operators").await.unwrap();
    }

    #[tokio::test(flavor = "multi_thread", worker_threads = 2)]
    async fn should_pass_selectors_v2() {
        run_fixture("selectors").await.unwrap();
    }

    #[tokio::test(flavor = "multi_thread", worker_threads = 2)]
    async fn should_pass_subquery_v2() {
        run_fixture("subquery").await.unwrap();
    }

    #[tokio::test(flavor = "multi_thread", worker_threads = 2)]
    async fn should_pass_vector_matching_v2() {
        run_fixture("vector_matching").await.unwrap();
    }

    /// Verifies that the v2 harness itself is wired up correctly even when no
    /// fixture is present. This is a smoke test for the router — if
    /// `run_test_v2` itself can't evaluate a trivial load + eval pair, every
    /// fixture-level test above would fail for reasons unrelated to the
    /// engine, and this test isolates that.
    #[tokio::test]
    async fn should_route_trivial_fixture_through_v2() {
        // given
        let content = "\nload 5m\n  metric 1 2 3\n\neval instant at 10m\n  metric\n    {} 3\n";

        // when
        let result = run_test_v2("smoke", content).await;

        // then
        assert!(result.is_ok(), "smoke-test harness failed: {result:?}");
    }

    /// Smoke perf snapshot for RFC 0007 Phase 6 acceptance. Synthesises a
    /// counter metric with modest cardinality, runs
    /// `sum by (pod) (rate(http_requests_total[5m]))` over a 6h range via
    /// [`Tsdb::eval_query_range_v2`], reports median wall-time across 5
    /// iterations. Not a true criterion benchmark — the acceptance criterion
    /// only asks for a recorded number. Ignored by default so it doesn't
    /// slow the normal test run; invoke with
    /// `cargo test --features promql-v2 v2_harness_perf_smoke -- --ignored --nocapture`.
    #[tokio::test(flavor = "multi_thread", worker_threads = 2)]
    #[ignore]
    async fn v2_harness_perf_smoke() {
        use crate::model::QueryOptions;
        use std::time::{Duration, UNIX_EPOCH};

        // Synthesise a 100-pod × 3-instance counter: 300 series, 1 sample
        // per 30 s across 6 h → 720 samples per series, ~216k sample writes
        // in total. Small enough to populate quickly in the InMemoryStorage
        // test TSDB; large enough for the perf signal to be non-trivial.
        let tsdb = new_test_storage();
        let step_secs = 30u64;
        let range_secs = 6 * 3600u64;
        let num_steps = range_secs / step_secs;
        // 100 pods × 3 instances = 300 series — matches the RFC 0007
        // Phase 6 acceptance target now that 6.3.1 removed the
        // aggregate-panic cardinality cap that originally clipped this
        // to 30 series.
        let num_pods = 100usize;
        let num_instances = 3usize;

        let mut series: Vec<SeriesLoad> = Vec::with_capacity(num_pods * num_instances);
        for pod_idx in 0..num_pods {
            for inst_idx in 0..num_instances {
                let labels = std::collections::HashMap::from([
                    ("__name__".to_string(), "http_requests_total".to_string()),
                    ("pod".to_string(), format!("pod-{pod_idx}")),
                    ("instance".to_string(), format!("inst-{inst_idx}")),
                ]);
                let mut values = Vec::with_capacity(num_steps as usize);
                for step in 0..num_steps {
                    // Monotonically increasing counter, +1 per step.
                    values.push((step as i64, step as f64));
                }
                series.push(SeriesLoad { labels, values });
            }
        }
        load_series(&tsdb, Duration::from_secs(step_secs), &series)
            .await
            .expect("load_series failed");

        let query = "sum by (pod) (rate(http_requests_total[5m]))";
        let start = UNIX_EPOCH;
        let end = UNIX_EPOCH + Duration::from_secs(range_secs);
        let step = Duration::from_secs(step_secs);
        let opts = QueryOptions::default();

        // Warmup.
        let _ = tsdb
            .eval_query_range_v2(query, start..=end, step, &opts)
            .await
            .expect("warmup failed");

        // Measure 5 runs, take median.
        let mut samples_ms: Vec<u128> = Vec::with_capacity(5);
        for _ in 0..5 {
            let t0 = std::time::Instant::now();
            let r = tsdb
                .eval_query_range_v2(query, start..=end, step, &opts)
                .await
                .expect("range eval failed");
            let elapsed = t0.elapsed();
            samples_ms.push(elapsed.as_millis());
            // Ensure the output isn't optimised away.
            assert!(!r.into_matrix().is_empty(), "empty result");
        }
        samples_ms.sort();
        let median = samples_ms[samples_ms.len() / 2];
        eprintln!(
            "v2 perf smoke: {} steps × {} series ({} pods × {} instances): \
             median={} ms, samples={:?}",
            num_steps,
            num_pods * num_instances,
            num_pods,
            num_instances,
            median,
            samples_ms
        );
    }

    /// Surfaces every `.test` file we haven't hand-wired above. Fails loudly
    /// if a new fixture is added, so the v2 harness keeps up with the v1
    /// corpus without silent drift.
    #[test]
    fn should_cover_every_fixture_file() {
        let files = discover_test_files();
        let known: std::collections::HashSet<&str> = [
            "aggregators",
            "at_modifier",
            "functions",
            "name_label_dropping",
            "offset",
            "operators",
            "selectors",
            "subquery",
            "vector_matching",
        ]
        .into_iter()
        .collect();

        let missing: Vec<_> = files
            .iter()
            .filter_map(|p| p.file_stem().and_then(|s| s.to_str()))
            .filter(|stem| !known.contains(*stem))
            .map(|s| s.to_string())
            .collect();

        assert!(
            missing.is_empty(),
            "v2 harness missing entries for fixtures: {missing:?}"
        );
    }
}
